services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: road_accidents
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --local-infile=1

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
